name: CI and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install

#      - name: Run tests
#        run: npm run test --passWithNoTests

      - name: Build the project
        run: npm run build

      - name: Lint the project (optional)
        run: npm run lint

      - name: Build Docker image
        run: |
          docker build -t catalog_bot_api .
          docker images

      - name: Save Docker image
        run: |
          docker save catalog_bot_api | bzip2 > catalog_bot_api.tar.bz2

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: catalog_bot_api.tar.bz2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker image to server
        run: |
          scp -o StrictHostKeyChecking=no catalog_bot_api.tar.bz2 narmatoff@31.128.38.77:~/catalog-bot/

      - name: Deploy Docker image to server
        run: |
          ssh -o StrictHostKeyChecking=no narmatoff@31.128.38.77 << 'EOF'
          cd ~/catalog-bot
          bunzip2 < catalog_bot_api.tar.bz2 | docker load
          docker stop catalog_bot_api || true
          docker rm catalog_bot_api || true
          docker run -d --name catalog_bot_api -p 3000:3000 catalog_bot_api
          EOF
